In [1]:
pip install pandas scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [45]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load the dataset
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ZOD-CSV-Datasets/PL_ZOD_Data.csv')

# Sort data by timestamp
data = data.sort_values(by='Time').reset_index(drop=True)

# Define speed ranges
def categorize_speed(speed):
    if speed < 10:
        return '0-10'
    elif speed < 20:
        return '10-20'
    elif speed < 30:
        return '20-30'
    elif speed < 40:
        return '30-40'
    elif speed < 50:
        return '40-50'
    elif speed < 60:
        return '50-60'
    elif speed < 70:
        return '60-70'
    elif speed < 80:
        return '70-80'
    elif speed < 90:
        return '80-90'
    elif speed < 100:
        return '90-100'
    elif speed < 110:
        return '100-110'
    elif speed < 120:
        return '110-120'
    elif speed < 130:
        return '120-130'
    else:
        return '130+'

# Apply speed categorization
data['Speed_Category'] = data['Speed (kph)'].apply(categorize_speed)

# Create next frame features
next_frame_cols = ['Number of Vehicles', 'Number of Lane Instances', 'Number of Pedestrians', 'Number of Traffic Lights', 'Number of Traffic Signs', 'Speed (kph)', 'Speed_Category']
for col in next_frame_cols:
    data[f'{col}_next'] = data[col].shift(-1)

# Drop the last row with NaN values for next frame features
data = data.dropna()

# Extract relevant features and target for training
features = ['Number of Vehicles', 'Number of Lane Instances', 'Number of Pedestrians', 'Number of Traffic Lights', 'Number of Traffic Signs', 'Weather Condition', 'Road Condition', 'Time of Day', 'Road Type']
next_frame_features = [f'{col}_next' for col in next_frame_cols[:-2]]  # Exclude 'Speed_Category_next' & 'Speed (kph)_next'
all_features = features + next_frame_features

X = data[all_features]
y = data['Speed_Category_next']

# Encode categorical variables
le_weather = LabelEncoder()
le_road_cond = LabelEncoder()
le_time_of_day = LabelEncoder()
le_road_type = LabelEncoder()

X['Weather Condition'] = le_weather.fit_transform(X['Weather Condition'])
X['Road Condition'] = le_road_cond.fit_transform(X['Road Condition'])
X['Time of Day'] = le_time_of_day.fit_transform(X['Time of Day'])
X['Road Type'] = le_road_type.fit_transform(X['Road Type'])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest Classifier
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)

# Make predictions
y_pred = rfc.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

# Display feature importances
importances = pd.Series(rfc.feature_importances_, index=all_features).sort_values(ascending=False)
print(importances)

<ipython-input-45-32ea25cf2c8d>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Weather Condition'] = le_weather.fit_transform(X['Weather Condition'])
<ipython-input-45-32ea25cf2c8d>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Road Condition'] = le_road_cond.fit_transform(X['Road Condition'])
<ipython-input-45-32ea25cf2c8d>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Time of Day'] = le_time_of_day.fit_transform(X['Time of Day'])
<ipython-input-45-32ea25cf2c8d>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Road Type'] = le_road_type.fit_transform(X['Road Type'])

              precision    recall  f1-score   support

        0-10       0.36      0.26      0.30       603
       10-20       0.25      0.05      0.08       449
     100-110       0.50      0.39      0.44        18
     110-120       0.27      0.33      0.30        12
     120-130       0.35      0.41      0.38        22
       20-30       0.27      0.27      0.27       849
       30-40       0.27      0.32      0.30      1151
       40-50       0.29      0.44      0.35      1206
       50-60       0.27      0.25      0.26       832
       60-70       0.25      0.19      0.22       426
       70-80       0.16      0.09      0.12       156
       80-90       0.29      0.03      0.06        61
      90-100       0.25      0.03      0.06        32

    accuracy                           0.28      5817
   macro avg       0.29      0.24      0.24      5817
weighted avg       0.28      0.28      0.27      5817

[[155  12   0   0   0 115 162 135  16   6   2   0   0]
 [ 44  22   0   0   0 126 119 107  24   5   2   0   0]
 [  0   0   7   3   2   0   0   2   0   2   2   0   0]
 [  0   0   1   4   2   0   1   0   0   2   2   0   0]
 [  0   0   0   2   9   0   0   2   3   3   2   1   0]
 [ 74  24   0   0   0 227 257 201  52  11   3   0   0]
 [ 90  16   0   0   0 193 368 376  83  20   4   1   0]
 [ 37   7   0   1   0 106 288 527 187  48   5   0   0]
 [ 30   5   0   0   1  59 108 324 208  76  19   0   2]
 [  5   3   2   2   1  17  24 137 131  83  21   0   0]
 [  0   0   0   1   1   5  13  22  48  50  14   1   1]
 [  1   0   1   1   2   0   2   7  16  21   8   2   0]
 [  0   0   3   1   8   1   0   3   6   4   3   2   1]]
Number of Traffic Signs          0.111408
Number of Traffic Signs_next     0.111032
Number of Vehicles_next          0.106461
Number of Vehicles               0.106000
Number of Lane Instances         0.083798
Number of Lane Instances_next    0.083556
Number of Traffic Lights_next    0.079054
Number of Traffic Lights         0.074924
Number of Pedestrians_next       0.065002
Number of Pedestrians            0.064481
Weather Condition                0.053650
Road Type                        0.026771
Road Condition                   0.017625
Time of Day                      0.016240
dtype: float64

In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load the dataset
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ZOD-CSV-Datasets/PL_ZOD_Data.csv')

# Sort data by timestamp
data = data.sort_values(by='Time').reset_index(drop=True)

# Create lag features (previous frame)
for col in ['Number of Vehicles', 'Number of Lane Instances', 'Number of Pedestrians', 'Number of Traffic Lights', 'Number of Traffic Signs', 'Speed (kph)']:
    data[f'{col}_prev'] = data[col].shift(1)

# Create difference features
for col in ['Number of Vehicles', 'Number of Lane Instances', 'Number of Pedestrians', 'Number of Traffic Lights', 'Number of Traffic Signs', 'Speed (kph)']:
    data[f'{col}_diff'] = data[col] - data[f'{col}_prev']

# Drop the first row with NaN values from lag feature creation
data = data.dropna().reset_index(drop=True)

print(data.head())

# Encode categorical variables
categorical_cols = ['Weather Condition', 'Road Condition', 'Time of Day', 'Road Type']
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

# Define speed ranges
def speed_range(speed):
    if speed < 10:
        return '0-10'
    elif speed < 20:
        return '10-20'
    elif speed < 30:
        return '20-30'
    elif speed < 40:
        return '30-40'
    elif speed < 50:
        return '40-50'
    elif speed < 60:
        return '50-60'
    elif speed < 70:
        return '60-70'
    elif speed < 80:
        return '70-80'
    elif speed < 90:
        return '80-90'
    elif speed < 100:
        return '90-100'
    elif speed < 110:
        return '100-110'
    elif speed < 120:
        return '110-120'
    elif speed < 130:
        return '120-130'
    elif speed < 140:
        return '130-140'
    elif speed < 150:
        return '140-150'
    else:
        return '150+'


# Apply speed range function to create target labels
data['Speed Range'] = data['Speed (kph)'].apply(speed_range)

# Features and target variable
features = ['Number of Vehicles', 'Number of Lane Instances', 'Number of Pedestrians', 'Number of Traffic Lights',
            'Number of Traffic Signs', 'Speed (kph)_prev', 'Number of Vehicles_diff', 'Number of Lane Instances_diff',
            'Number of Pedestrians_diff', 'Number of Traffic Lights_diff', 'Number of Traffic Signs_diff'] + categorical_cols
target = 'Speed Range'

# Split the data into train and test sets
X = data[features]
y = data[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

# Feature importance
feature_importances = pd.DataFrame(clf.feature_importances_, index=features, columns=['importance']).sort_values('importance', ascending=False)
print(feature_importances)

   Frame ID Country Code  Longitude   Latitude  \
0     64118           PL  19.054200  50.266932
1     94286           PL  19.111246  50.311502
2     26317           PL  19.110567  50.313415
3     90989           PL  19.107478  50.328272
4     72276           PL  19.043326  50.262459

                               Time  Weather Condition Road Condition  \
0  2021-03-26 08:37:26.774423+00:00  partly-cloudy-day         normal
1  2021-03-26 08:48:26.883220+00:00  partly-cloudy-day         normal
2  2021-03-26 08:48:48.216753+00:00  partly-cloudy-day         normal
3  2021-03-26 09:16:17.106787+00:00  partly-cloudy-day         normal
4  2021-03-26 09:25:25.114849+00:00  partly-cloudy-day         normal

  Time of Day       Road Type  Number of Vehicles  ...  \
0         day  arterial-urban                  15  ...
1         day  arterial-rural                  18  ...
2         day  arterial-urban                  10  ...
3         day  arterial-urban                   4  ...
4         day  arterial-urban                  15  ...

   Number of Pedestrians_prev  Number of Traffic Lights_prev  \
0                         5.0                           29.0
1                         0.0                            0.0
2                         0.0                            8.0
3                         0.0                           17.0
4                         0.0                            0.0

   Number of Traffic Signs_prev  Speed (kph)_prev  Number of Vehicles_diff  \
0                          52.0         35.972596                    -20.0
1                          19.0         70.555278                      3.0
2                          10.0         35.674392                     -8.0
3                          17.0          4.990055                     -6.0
4                           1.0         68.665545                     11.0

   Number of Lane Instances_diff  Number of Pedestrians_diff  \
0                            2.0                        -5.0
1                            0.0                         0.0
2                            0.0                         0.0
3                           -4.0                         0.0
4                            7.0                         1.0

   Number of Traffic Lights_diff  Number of Traffic Signs_diff  \
0                          -29.0                         -33.0
1                            8.0                          -9.0
2                            9.0                           7.0
3                          -17.0                         -16.0
4                            0.0                          32.0

   Speed (kph)_diff
0         34.582681
1        -34.880886
2        -30.684337
3         63.675490
4         -9.435224

[5 rows x 29 columns]
              precision    recall  f1-score   support

        0-10       0.43      0.29      0.35       603
       10-20       0.31      0.07      0.12       449
     100-110       0.50      0.50      0.50        18
     110-120       0.50      0.42      0.45        12
     120-130       0.77      0.77      0.77        22
       20-30       0.35      0.40      0.37       849
       30-40       0.40      0.45      0.42      1151
       40-50       0.44      0.59      0.51      1206
       50-60       0.49      0.51      0.50       832
       60-70       0.51      0.47      0.49       426
       70-80       0.48      0.40      0.44       156
       80-90       0.43      0.16      0.24        61
      90-100       0.52      0.34      0.42        32

    accuracy                           0.43      5817
   macro avg       0.47      0.41      0.43      5817
weighted avg       0.43      0.43      0.42      5817

[[174  30   0   0   0 129 126 103  37   3   1   0   0]
 [ 40  33   0   0   0 179 103  71  18   5   0   0   0]
 [  0   0   9   3   0   0   0   0   1   0   2   0   3]
 [  0   0   3   5   2   0   1   0   0   0   0   0   1]
 [  0   0   0   1  17   1   0   1   0   1   0   0   1]
 [ 68  29   0   0   0 338 256 123  26   6   2   1   0]
 [ 67   6   0   0   0 208 513 291  56   9   0   1   0]
 [ 33   4   0   0   0  71 218 714 140  22   4   0   0]
 [ 17   2   0   0   0  24  40 235 422  84   5   2   1]
 [  4   1   1   0   0   3  12  59 122 200  23   0   1]
 [  0   0   0   0   2   0   1  13  23  49  62   4   2]
 [  0   0   1   0   1   0   0   1  11  12  24  10   1]
 [  0   0   4   1   0   1   1   1   1   1   6   5  11]]
                               importance
Speed (kph)_prev                 0.203712
Number of Traffic Signs_diff     0.084979
Number of Traffic Signs          0.082792
Number of Vehicles_diff          0.082764
Number of Vehicles               0.078397
Number of Traffic Lights_diff    0.070990
Number of Lane Instances_diff    0.069610
Number of Lane Instances         0.062155
Number of Traffic Lights         0.061175
Number of Pedestrians_diff       0.056428
Number of Pedestrians            0.050247
Weather Condition                0.042500
Road Type                        0.026608
Road Condition                   0.014080
Time of Day                      0.013564

In [11]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.25.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.64.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.43.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (1.2.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2024.7.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow) (2.1.5)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report, confusion_matrix

# Load the dataset
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ZOD-CSV-Datasets/SE_ZOD_Data.csv')

# Sort data by timestamp
data = data.sort_values(by='Time').reset_index(drop=True)

# Create lag features (previous frame)
for col in ['Number of Vehicles', 'Number of Lane Instances', 'Number of Pedestrians', 'Number of Traffic Lights', 'Number of Traffic Signs', 'Speed (kph)']:
    data[f'{col}_prev'] = data[col].shift(1)

# Create difference features
for col in ['Number of Vehicles', 'Number of Lane Instances', 'Number of Pedestrians', 'Number of Traffic Lights', 'Number of Traffic Signs', 'Speed (kph)']:
    data[f'{col}_diff'] = data[col] - data[f'{col}_prev']

# Drop the first row with NaN values from lag feature creation
data = data.dropna().reset_index(drop=True)

# Encode categorical variables
categorical_cols = ['Weather Condition', 'Road Condition', 'Time of Day', 'Road Type']
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

# Define speed ranges
def speed_range(speed):
    if speed < 10:
        return 0
    elif speed < 20:
        return 1
    elif speed < 30:
        return 2
    elif speed < 40:
        return 3
    elif speed < 50:
        return 4
    elif speed < 60:
        return 5
    elif speed < 70:
        return 6
    elif speed < 80:
        return 7
    elif speed < 90:
        return 8
    elif speed < 100:
        return 9
    elif speed < 110:
        return 10
    elif speed < 120:
        return 11
    elif speed < 130:
        return 12
    elif speed < 140:
        return 13
    elif speed < 150:
        return 14
    else:
        return 15

# Apply speed range function to create target labels
data['Speed Range'] = data['Speed (kph)'].apply(speed_range)

# Features and target variable
features = ['Number of Vehicles', 'Number of Lane Instances', 'Number of Pedestrians', 'Number of Traffic Lights',
            'Number of Traffic Signs', 'Speed (kph)_prev', 'Number of Vehicles_diff', 'Number of Lane Instances_diff',
            'Number of Pedestrians_diff', 'Number of Traffic Lights_diff', 'Number of Traffic Signs_diff'] + categorical_cols
target = 'Speed Range'

# Split the data into train and test sets
X = data[features]
y = data[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert target variable to categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Build the neural network
model = Sequential()
model.add(Dense(128, input_dim=X_train.shape[1], activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(y_train.shape[1], activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

print(classification_report(y_test_classes, y_pred_classes))
print(confusion_matrix(y_test_classes, y_pred_classes))

Epoch 1/50
338/338 [==============================] - 5s 7ms/step - loss: 1.9714 - accuracy: 0.2585 - val_loss: 1.6728 - val_accuracy: 0.3510
Epoch 2/50
338/338 [==============================] - 1s 3ms/step - loss: 1.7462 - accuracy: 0.3022 - val_loss: 1.6167 - val_accuracy: 0.3551
Epoch 3/50
338/338 [==============================] - 1s 3ms/step - loss: 1.6901 - accuracy: 0.3285 - val_loss: 1.5933 - val_accuracy: 0.3795
Epoch 4/50
338/338 [==============================] - 1s 3ms/step - loss: 1.6579 - accuracy: 0.3427 - val_loss: 1.5631 - val_accuracy: 0.3947
Epoch 5/50
338/338 [==============================] - 1s 3ms/step - loss: 1.6353 - accuracy: 0.3473 - val_loss: 1.5496 - val_accuracy: 0.4010
Epoch 6/50
338/338 [==============================] - 1s 3ms/step - loss: 1.6191 - accuracy: 0.3614 - val_loss: 1.5316 - val_accuracy: 0.4043
Epoch 7/50
338/338 [==============================] - 1s 3ms/step - loss: 1.6009 - accuracy: 0.3681 - val_loss: 1.5291 - val_accuracy: 0.4143
Epoch 8/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5962 - accuracy: 0.3663 - val_loss: 1.5120 - val_accuracy: 0.4195
Epoch 9/50
338/338 [==============================] - 2s 6ms/step - loss: 1.5826 - accuracy: 0.3703 - val_loss: 1.5158 - val_accuracy: 0.4065
Epoch 10/50
338/338 [==============================] - 2s 5ms/step - loss: 1.5787 - accuracy: 0.3774 - val_loss: 1.5133 - val_accuracy: 0.4106
Epoch 11/50
338/338 [==============================] - 2s 5ms/step - loss: 1.5671 - accuracy: 0.3779 - val_loss: 1.5254 - val_accuracy: 0.4065
Epoch 12/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5629 - accuracy: 0.3790 - val_loss: 1.5036 - val_accuracy: 0.4117
Epoch 13/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5610 - accuracy: 0.3847 - val_loss: 1.4961 - val_accuracy: 0.4221
Epoch 14/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5466 - accuracy: 0.3914 - val_loss: 1.4904 - val_accuracy: 0.4280
Epoch 15/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5441 - accuracy: 0.3898 - val_loss: 1.4881 - val_accuracy: 0.4243
Epoch 16/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5406 - accuracy: 0.3883 - val_loss: 1.4796 - val_accuracy: 0.4272
Epoch 17/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5375 - accuracy: 0.3938 - val_loss: 1.4871 - val_accuracy: 0.4180
Epoch 18/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5356 - accuracy: 0.3902 - val_loss: 1.4873 - val_accuracy: 0.4224
Epoch 19/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5302 - accuracy: 0.3976 - val_loss: 1.4882 - val_accuracy: 0.4147
Epoch 20/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5271 - accuracy: 0.3938 - val_loss: 1.4860 - val_accuracy: 0.4180
Epoch 21/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5235 - accuracy: 0.3981 - val_loss: 1.4754 - val_accuracy: 0.4276
Epoch 22/50
338/338 [==============================] - 1s 4ms/step - loss: 1.5204 - accuracy: 0.3955 - val_loss: 1.4858 - val_accuracy: 0.4328
Epoch 23/50
338/338 [==============================] - 2s 5ms/step - loss: 1.5218 - accuracy: 0.4011 - val_loss: 1.4847 - val_accuracy: 0.4210
Epoch 24/50
338/338 [==============================] - 2s 5ms/step - loss: 1.5136 - accuracy: 0.4021 - val_loss: 1.4796 - val_accuracy: 0.4150
Epoch 25/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5115 - accuracy: 0.4033 - val_loss: 1.4853 - val_accuracy: 0.4258
Epoch 26/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5066 - accuracy: 0.4061 - val_loss: 1.4809 - val_accuracy: 0.4221
Epoch 27/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5052 - accuracy: 0.4021 - val_loss: 1.4878 - val_accuracy: 0.4065
Epoch 28/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5014 - accuracy: 0.4089 - val_loss: 1.4839 - val_accuracy: 0.4250
Epoch 29/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5014 - accuracy: 0.4015 - val_loss: 1.4788 - val_accuracy: 0.4136
Epoch 30/50
338/338 [==============================] - 1s 3ms/step - loss: 1.5053 - accuracy: 0.3974 - val_loss: 1.4754 - val_accuracy: 0.4102
Epoch 31/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4993 - accuracy: 0.4041 - val_loss: 1.4731 - val_accuracy: 0.4180
Epoch 32/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4969 - accuracy: 0.4046 - val_loss: 1.4786 - val_accuracy: 0.4210
Epoch 33/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4976 - accuracy: 0.4002 - val_loss: 1.4779 - val_accuracy: 0.4217
Epoch 34/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4934 - accuracy: 0.4064 - val_loss: 1.4790 - val_accuracy: 0.4136
Epoch 35/50
338/338 [==============================] - 2s 5ms/step - loss: 1.4970 - accuracy: 0.4025 - val_loss: 1.4801 - val_accuracy: 0.4128
Epoch 36/50
338/338 [==============================] - 2s 5ms/step - loss: 1.4903 - accuracy: 0.4102 - val_loss: 1.4760 - val_accuracy: 0.4154
Epoch 37/50
338/338 [==============================] - 2s 4ms/step - loss: 1.4819 - accuracy: 0.4056 - val_loss: 1.4819 - val_accuracy: 0.4132
Epoch 38/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4869 - accuracy: 0.4108 - val_loss: 1.4807 - val_accuracy: 0.4217
Epoch 39/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4848 - accuracy: 0.4067 - val_loss: 1.4898 - val_accuracy: 0.4047
Epoch 40/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4872 - accuracy: 0.4136 - val_loss: 1.4743 - val_accuracy: 0.4217
Epoch 41/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4837 - accuracy: 0.4061 - val_loss: 1.4800 - val_accuracy: 0.4176
Epoch 42/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4742 - accuracy: 0.4112 - val_loss: 1.4736 - val_accuracy: 0.4247
Epoch 43/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4702 - accuracy: 0.4119 - val_loss: 1.4745 - val_accuracy: 0.4180
Epoch 44/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4727 - accuracy: 0.4087 - val_loss: 1.4805 - val_accuracy: 0.4154
Epoch 45/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4754 - accuracy: 0.4102 - val_loss: 1.4811 - val_accuracy: 0.4191
Epoch 46/50
338/338 [==============================] - 1s 4ms/step - loss: 1.4732 - accuracy: 0.4138 - val_loss: 1.4813 - val_accuracy: 0.4247
Epoch 47/50
338/338 [==============================] - 2s 5ms/step - loss: 1.4669 - accuracy: 0.4185 - val_loss: 1.4821 - val_accuracy: 0.4239
Epoch 48/50
338/338 [==============================] - 2s 5ms/step - loss: 1.4711 - accuracy: 0.4096 - val_loss: 1.4814 - val_accuracy: 0.4176
Epoch 49/50
338/338 [==============================] - 1s 4ms/step - loss: 1.4677 - accuracy: 0.4108 - val_loss: 1.4778 - val_accuracy: 0.4306
Epoch 50/50
338/338 [==============================] - 1s 3ms/step - loss: 1.4664 - accuracy: 0.4137 - val_loss: 1.4795 - val_accuracy: 0.4195
106/106 [==============================] - 0s 2ms/step
              precision    recall  f1-score   support

           0       0.38      0.27      0.31       222
           1       0.40      0.21      0.27       342
           2       0.43      0.37      0.40       681
           3       0.46      0.67      0.55       872
           4       0.39      0.38      0.38       387
           5       0.33      0.15      0.21       179
           6       0.30      0.15      0.20       141
           7       0.32      0.54      0.40       177
           8       0.34      0.25      0.29       141
           9       0.45      0.64      0.53       139
          10       0.53      0.51      0.52        81
          11       0.00      0.00      0.00        14
          12       0.00      0.00      0.00         0

    accuracy                           0.42      3376
   macro avg       0.33      0.32      0.31      3376
weighted avg       0.41      0.42      0.40      3376

[[ 59  27  47  75  10   1   2   1   0   0   0   0   0]
 [ 31  71 125 100   9   2   2   1   0   0   1   0   0]
 [ 26  57 250 294  41   6   1   5   0   0   1   0   0]
 [ 31  14 121 585  96  11   2   9   1   2   0   0   0]
 [  7   2  27 159 147  15   8  14   3   3   2   0   0]
 [  0   3   8  34  50  27  15  31   3   7   1   0   0]
 [  0   1   0  10  17   8  21  63  13   6   2   0   0]
 [  0   0   0   1   4   6  13  95  33  23   2   0   0]
 [  0   0   0   0   0   3   3  50  35  44   6   0   0]
 [  0   0   0   1   2   2   1  21  12  89  11   0   0]
 [  0   1   0   0   3   0   0   9   1  25  41   0   1]
 [  0   0   0   0   0   1   1   0   1   1  10   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
import pandas as pd

# Load the CSV file
file_path = '/content/drive/My Drive/Colab Notebooks/PL_ZOD_Data.csv'
data = pd.read_csv(file_path)

# Display the first few rows of the dataframe
data.head()

,Frame ID,Country Code,Longitude,Latitude,Time,Weather Condition,Road Condition,Time of Day,Road Type,Number of Vehicles,Number of Lane Instances,Number of Pedestrians,Number of Traffic Lights,Number of Traffic Signs,Speed (kph),next_frame_id,distance_to_next
0,48035,PL,19.010398,50.267241,2021-03-26 08:33:48.004884+00:00,partly-cloudy-day,normal,day,city,35,5,5,29,52,35.972596,37380,0.002771
1,64118,PL,19.054200,50.266932,2021-03-26 08:37:26.774423+00:00,partly-cloudy-day,normal,day,arterial-urban,15,7,0,0,19,70.555278,99828,0.005885
2,94286,PL,19.111246,50.311502,2021-03-26 08:48:26.883220+00:00,partly-cloudy-day,normal,day,arterial-rural,18,7,0,8,10,35.674392,26317,0.002031
3,26317,PL,19.110567,50.313415,2021-03-26 08:48:48.216753+00:00,partly-cloudy-day,normal,day,arterial-urban,10,7,0,17,17,4.990055,94286,0.002031
4,90989,PL,19.107478,50.328272,2021-03-26 09:16:17.106787+00:00,partly-cloudy-day,normal,day,arterial-urban,4,3,0,0,1,68.665545,89257,0.006284

In [ ]:
import pandas as pd

# Step 1: Sort by Time
data.sort_values(by='Time', inplace=True)

# Step 2: Calculate differences between consecutive rows
data['speed_change'] = data['Speed (kph)'].diff()
data['number_of_vehicles_change'] = data['Number of Vehicles'].diff()
data['number_of_lane_instances_change'] = data['Number of Lane Instances'].diff()
data['number_of_pedestrians_change'] = data['Number of Pedestrians'].diff()
data['number_of_traffic_lights_change'] = data['Number of Traffic Lights'].diff()
data['number_of_traffic_signs_change'] = data['Number of Traffic Signs'].diff()

# Step 3: Encode categorical variables
data['weather_change'] = (data['Weather Condition'] != data['Weather Condition'].shift()).astype(int)
data['road_condition_change'] = (data['Road Condition'] != data['Road Condition'].shift()).astype(int)
data['time_of_day_change'] = (data['Time of Day'] != data['Time of Day'].shift()).astype(int)
data['road_type_change'] = (data['Road Type'] != data['Road Type'].shift()).astype(int)

# Step 4: One-hot encode categorical features
data = pd.get_dummies(data, columns=['weather_change', 'road_condition_change', 'time_of_day_change', 'road_type_change'])

# Step 5: Select relevant features in the specified order
features = [
    'number_of_vehicles_change',
    'number_of_lane_instances_change', 'number_of_pedestrians_change',
    'number_of_traffic_lights_change', 'number_of_traffic_signs_change',
    'weather_change_0', 'weather_change_1',
    'road_condition_change_0', 'road_condition_change_1',
    'time_of_day_change_0', 'time_of_day_change_1',
    'road_type_change_0', 'road_type_change_1'
]

# Drop NaN values resulting from diff() operation in the first row
data.dropna(inplace=True)

# Display the first few rows of the processed data and selected features
selected_data = data[features]
selected_data.head()

,number_of_vehicles_change,number_of_lane_instances_change,number_of_pedestrians_change,number_of_traffic_lights_change,number_of_traffic_signs_change,weather_change_0,weather_change_0,weather_change_0,weather_change_1,weather_change_1,...,time_of_day_change_0,time_of_day_change_1,time_of_day_change_1,time_of_day_change_1,road_type_change_0,road_type_change_0,road_type_change_0,road_type_change_1,road_type_change_1,road_type_change_1
3,-8.0,0.0,0.0,9.0,7.0,True,True,True,False,False,...,True,False,False,False,False,False,False,True,True,True
4,-6.0,-4.0,0.0,-17.0,-16.0,True,True,True,False,False,...,True,False,False,False,True,True,True,False,False,False
5,11.0,7.0,1.0,0.0,32.0,True,True,True,False,False,...,True,False,False,False,True,True,True,False,False,False
6,-5.0,-6.0,-1.0,9.0,0.0,True,True,True,False,False,...,True,False,False,False,True,True,True,False,False,False
7,16.0,6.0,3.0,19.0,19.0,True,True,True,False,False,...,True,False,False,False,True,True,True,False,False,False

In [ ]:
# Calculate the difference in speed between consecutive frames
merged_data['speed_change'] = merged_data['Speed (kph)_end'] - merged_data['Speed (kph)_start']

# Calculate the difference for other relevant features
merged_data['longitude_change'] = merged_data['Longitude_end'] - merged_data['Longitude_start']
merged_data['latitude_change'] = merged_data['Latitude_end'] - merged_data['Latitude_start']
merged_data['number_of_vehicles_change'] = merged_data['Number of Vehicles_end'] - merged_data['Number of Vehicles_start']
merged_data['number_of_lane_instances_change'] = merged_data['Number of Lane Instances_end'] - merged_data['Number of Lane Instances_start']
merged_data['number_of_pedestrians_change'] = merged_data['Number of Pedestrians_end'] - merged_data['Number of Pedestrians_start']
merged_data['number_of_traffic_lights_change'] = merged_data['Number of Traffic Lights_end'] - merged_data['Number of Traffic Lights_start']
merged_data['number_of_traffic_signs_change'] = merged_data['Number of Traffic Signs_end'] - merged_data['Number of Traffic Signs_start']

# Encode categorical variables
merged_data['weather_change'] = merged_data['Weather Condition_end'] != merged_data['Weather Condition_start']
merged_data['road_condition_change'] = merged_data['Road Condition_end'] != merged_data['Road Condition_start']
merged_data['time_of_day_change'] = merged_data['Time of Day_end'] != merged_data['Time of Day_start']
merged_data['road_type_change'] = merged_data['Road Type_end'] != merged_data['Road Type_start']

# One-hot encode the categorical features
merged_data = pd.get_dummies(merged_data, columns=['weather_change', 'road_condition_change', 'time_of_day_change', 'road_type_change'])

# Select the relevant features for modeling
features = [
    'longitude_change', 'latitude_change', 'number_of_vehicles_change',
    'number_of_lane_instances_change', 'number_of_pedestrians_change',
    'number_of_traffic_lights_change', 'number_of_traffic_signs_change'
] + [col for col in merged_data.columns if 'weather_change' in col or 'road_condition_change' in col or 'time_of_day_change' in col or 'road_type_change' in col]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Split the data into training and testing sets
X = data[features]
y = data['speed_change']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 317.40177370768544

In [ ]:
importances = model.feature_importances_
feature_importance = pd.DataFrame({'Feature': features, 'Importance': importances})
feature_importance.sort_values(by='Importance', ascending=False, inplace=True)

# Display feature importance
feature_importance

ValueError: All arrays must be of the same length

In [ ]:
import os

path = '/content/drive/My Drive/Colab Notebooks/ZODFullDataset/Frames/single_frames/000780'

# Check if the path exists
if os.path.exists(path):
    # Use os.walk to navigate through the directory
    folder_count = sum(os.path.isdir(os.path.join(path, entry)) for entry in os.listdir(path))
    print(f"Number of folders in '{path}': {folder_count}")
else:
    print("Specified path does not exist")

Number of folders in '/content/drive/My Drive/Colab Notebooks/ZODFullDataset/Frames/single_frames/000780': 1

In [ ]:
import os
import json
import pandas as pd
from datetime import datetime

base_path = '/content/drive/My Drive/Colab Notebooks/ZODMiniDataset/Frames/single_frames'

# Function to load metadata for all frames
def load_metadata(base_path):
    metadata = []
    for frame_id in os.listdir(base_path):
        frame_path = os.path.join(base_path, frame_id)
        if os.path.isdir(frame_path):
            metadata_path = os.path.join(frame_path, 'metadata.json')
            if os.path.exists(metadata_path):
                with open(metadata_path, 'r') as file:
                    data = json.load(file)
                    metadata.append(data)
    return pd.DataFrame(metadata)

# Filter rare instances and non-peak times
def filter_metadata(metadata):
    # Omit rows with rare weather and road conditions
    metadata = metadata[(metadata['scraped_weather'] != 'snow') & (metadata['road_condition'] != 'snow')]

    # Convert 'Time' to datetime
    metadata['time'] = pd.to_datetime(metadata['time'])

    # Define peak hours
    start_time = datetime.strptime("07:00:00", "%H:%M:%S").time()
    end_time = datetime.strptime("19:00:00", "%H:%M:%S").time()

    # Omit rows outside of peak times
    metadata = metadata[(metadata['time'].dt.time >= start_time) & (metadata['time'].dt.time <= end_time)]

    return metadata

# Load and filter metadata
metadata = load_metadata(base_path)
filtered_metadata = filter_metadata(metadata)

# Print the head of the filtered metadata
print(filtered_metadata.head())

  frame_id                             time country_code    scraped_weather  \
0   009158 2020-11-21 09:44:55.445654+00:00           DE             cloudy
1   018591 2020-07-24 07:08:56.778861+00:00           IT               rain
2   023996 2021-04-15 14:52:36.885711+00:00           PL               rain
3   029229 2021-05-02 14:22:06.780681+00:00           PL               rain
4   044953 2020-05-06 11:41:57.779576+00:00           SE  partly-cloudy-day

  collection_car road_type road_condition time_of_day  num_lane_instances  \
0          india      city         normal         day                   1
1          india      city         normal         day                   3
2          india      city            wet         day                   6
3           golf      city            wet         day                  10
4          india      city         normal         day                   0

   num_vehicles  num_vulnerable_vehicles  num_pedestrians  num_traffic_lights  \
0            26                        7                3                   3
1            25                        3                6                   7
2            18                        2                9                   9
3            22                        1                5                   6
4             5                        1                2                   0

   num_traffic_signs  longitude   latitude  solar_angle_elevation
0                 16   6.935002  50.942598              16.011264
1                 24   9.155494  45.467742              30.966537
2                 13  21.011181  52.200755              23.857361
3                 70  20.999896  52.230594              32.236646
4                  5  17.633240  59.853070              45.873165

<ipython-input-3-f7cf916b7e96>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['time'] = pd.to_datetime(metadata['time'])

In [ ]:
import os
import json
import pandas as pd
from datetime import datetime

base_path = '/content/drive/My Drive/Colab Notebooks/ZODMiniDataset/Frames/single_frames'

# Function to load metadata for all frames
def load_metadata(base_path):
    metadata = []
    for frame_id in os.listdir(base_path):
        frame_path = os.path.join(base_path, frame_id)
        if os.path.isdir(frame_path):
            metadata_path = os.path.join(frame_path, 'metadata.json')
            if os.path.exists(metadata_path):
                with open(metadata_path, 'r') as file:
                    data = json.load(file)
                    metadata.append(data)
    return pd.DataFrame(metadata)

# Filter rare instances and non-peak times
def filter_metadata(metadata, peak_hours):
    # Omit rows with rare weather and road conditions
    metadata = metadata[(metadata['scraped_weather'] != 'snow') & (metadata['road_condition'] != 'snow')]

    # Convert 'Time' to datetime
    metadata['time'] = pd.to_datetime(metadata['time'])

    # Filter based on peak hours
    filtered_metadata = metadata[metadata['time'].dt.time.apply(lambda t: any(start <= t <= end for start, end in peak_hours))]

    return filtered_metadata

# Load metadata
metadata = load_metadata(base_path)

# Define peak hours
peak_hours_1 = [(datetime.strptime("07:00:00", "%H:%M:%S").time(), datetime.strptime("19:00:00", "%H:%M:%S").time())]
peak_hours_2 = [
    (datetime.strptime("06:30:00", "%H:%M:%S").time(), datetime.strptime("09:30:00", "%H:%M:%S").time()),
    (datetime.strptime("16:30:00", "%H:%M:%S").time(), datetime.strptime("19:00:00", "%H:%M:%S").time())
]

# Filter metadata for both sets of peak hours
filtered_metadata_1 = filter_metadata(metadata, peak_hours_1)
filtered_metadata_2 = filter_metadata(metadata, peak_hours_2)

# Save to CSV files
filtered_metadata_1.to_csv('/content/drive/My Drive/Colab Notebooks/filtered_metadata_07_00_to_19_00.csv', index=False)
filtered_metadata_2.to_csv('/content/drive/My Drive/Colab Notebooks/filtered_metadata_06_30_to_09_30_and_16_30_to_19_00.csv', index=False)

# Print confirmation message
print("CSV files have been saved.")

CSV files have been saved.

<ipython-input-6-d3022add2390>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['time'] = pd.to_datetime(metadata['time'])
<ipython-input-6-d3022add2390>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['time'] = pd.to_datetime(metadata['time'])

In [ ]:
import cv2
import torch
import json
import os
import matplotlib.pyplot as plt

# Load a pre-trained YOLOv5 model (latest version)
model = torch.hub.load('ultralytics/yolov5', 'yolov5x')

# Function to detect objects in an image
def detect_objects(image_path):
    for file_name in os.listdir(image_path):
        if file_name.endswith('.jpg'):
            img_path = os.path.join(image_path, file_name)
            img = cv2.imread(img_path)
            results = model(img)
            return results.pandas().xyxy[0]
    return None

# Extract features from an image
def extract_annotations(annotation_path):
    with open(annotation_path, 'r') as file:
        annotations = json.load(file)
    return annotations

# Extract features from an image using both detections and annotations
def extract_features(image_path):
    # Detect objects using YOLO
    detections = detect_objects(image_path)
    if detections is None:
        print(f'No image file found in {image_path}')
        return None

    # Extract relevant annotation data
    vehicles = len(detections[detections['name'] == 'car'])
    pedestrians = len(detections[detections['name'] == 'person'])
    traffic_lights = len(detections[detections['name'] == 'traffic light'])

    # Combine detection results with annotations
    features = {
        'vehicles': vehicles,
        'pedestrians': pedestrians,
        'traffic_lights': traffic_lights
    }

    return features

# List of frame IDs
frame_ids = ['007674', '009158', '018591', '023996', '029229', '044953', '062592', '065838', '070221', '082291', '083430', '087912']

# Base path to the dataset
base_path = '/content/drive/My Drive/Colab Notebooks/ZODMiniDataset/Frames/single_frames'

# Dictionary to store features for each frame
all_features = {}

for frame_id in frame_ids:
    image_path = os.path.join(base_path, frame_id, 'camera_front_blur')
    features = extract_features(image_path)
    if features is not None:
        all_features[frame_id] = features

print(all_features)

/usr/local/lib/python3.10/dist-packages/torch/hub.py:293: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip

requirements: Ultralytics requirements ['gitpython>=3.1.30', 'pillow>=10.3.0', 'requests>=2.32.0'] not found, attempting AutoUpdate...
Collecting gitpython>=3.1.30
  Downloading GitPython-3.1.43-py3-none-any.whl (207 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 4.2 MB/s eta 0:00:00
Collecting pillow>=10.3.0
  Downloading pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 13.5 MB/s eta 0:00:00
Collecting requests>=2.32.0
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 142.7 MB/s eta 0:00:00
Collecting gitdb<5,>=4.0.1 (from gitpython>=3.1.30)
  Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 117.6 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.0) (2024.7.4)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython>=3.1.30)
  Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
Installing collected packages: smmap, requests, pillow, gitdb, gitpython
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.4.0
    Uninstalling Pillow-9.4.0:
      Successfully uninstalled Pillow-9.4.0
Successfully installed gitdb-4.0.11 gitpython-3.1.43 pillow-10.4.0 requests-2.32.3 smmap-5.0.1

requirements: AutoUpdate success ✅ 11.8s, installed 3 packages: ['gitpython>=3.1.30', 'pillow>=10.3.0', 'requests>=2.32.0']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

YOLOv5 🚀 2024-7-13 Python-3.10.12 torch-2.3.0+cu121 CPU

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5x.pt to yolov5x.pt...
100%|██████████| 166M/166M [00:00<00:00, 251MB/s]

Fusing layers...
YOLOv5x summary: 444 layers, 86705005 parameters, 0 gradients, 205.5 GFLOPs
Adding AutoShape...

{'007674': {'vehicles': 14, 'pedestrians': 0, 'traffic_lights': 0}, '009158': {'vehicles': 10, 'pedestrians': 0, 'traffic_lights': 0}, '018591': {'vehicles': 8, 'pedestrians': 2, 'traffic_lights': 3}, '023996': {'vehicles': 5, 'pedestrians': 1, 'traffic_lights': 1}, '029229': {'vehicles': 8, 'pedestrians': 0, 'traffic_lights': 0}, '044953': {'vehicles': 2, 'pedestrians': 1, 'traffic_lights': 0}, '062592': {'vehicles': 0, 'pedestrians': 1, 'traffic_lights': 0}, '065838': {'vehicles': 15, 'pedestrians': 1, 'traffic_lights': 5}, '070221': {'vehicles': 6, 'pedestrians': 1, 'traffic_lights': 0}, '082291': {'vehicles': 4, 'pedestrians': 0, 'traffic_lights': 0}, '083430': {'vehicles': 2, 'pedestrians': 0, 'traffic_lights': 7}, '087912': {'vehicles': 8, 'pedestrians': 0, 'traffic_lights': 0}}

In [ ]:
import cv2
import torch
import json
import os

# Load a pre-trained YOLO model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

def detect_objects(image_path):
    for file_name in os.listdir(image_path):
        if file_name.endswith('.jpg'):
            img = cv2.imread(os.path.join(image_path, file_name))
            results = model(img)
            return results.pandas().xyxy[0]
    return None

def extract_annotations(annotation_path):
    traffic_signs_path = os.path.join(annotation_path, 'object_detection.json')
    with open(traffic_signs_path, 'r') as file:
        annotations = json.load(file)

    # Filter annotations based on relevance to ego road and lane
    relevant_annotations = []
    for annotation in annotations:
        properties = annotation['properties']

        # Check conditions for relevance
        if (properties.get('is_for_ego_road') != 'False' and
            properties.get('is_for_ego_lane') != 'False' and
            properties.get('relative_position') in ['EgoLane', 'LeftAndEgoLane', 'RightAndEgoLane']):
            relevant_annotations.append(annotation)
        else:
            relevant_annotations.append(annotation)  # Include annotations where these properties are not defined

    return relevant_annotations


def count_objects(annotations, class_name):
    count = sum(1 for anno in annotations if anno['properties']['class'] == class_name)
    return count

def extract_features(image_path, annotation_path):
    # Load annotations
    annotations = extract_annotations(annotation_path)

    # Count relevant classes from annotations
    vehicle_count = count_objects(annotations, 'Vehicle')
    traffic_sign_count = count_objects(annotations, 'TrafficSign')
    traffic_signal_count = count_objects(annotations, 'TrafficSignal')
    pole_object_count = count_objects(annotations, 'PoleObject')
    pedestrian_count = count_objects(annotations, 'Pedestrian')
    vulnerable_vehicle_count = count_objects(annotations, 'VulnerableVehicle')
    traffic_guide_count = count_objects(annotations, 'TrafficGuide')

    # Combine counts
    features = {
        'vehicles': vehicle_count,
        'pedestrians': pedestrian_count,
        'traffic_signs': traffic_sign_count,
        'traffic_signals': traffic_signal_count,
        'pole_objects': pole_object_count,
        'vulnerable_vehicles': vulnerable_vehicle_count,
        'traffic_guides': traffic_guide_count
    }

    return features


# Example usage for multiple frames
frame_ids = ['007674', '009158', '018591', '023996', '029229', '044953', '062592', '065838', '070221', '082291', '083430', '087912']
base_path = '/content/drive/My Drive/Colab Notebooks/ZODMiniDataset/Frames/single_frames'

for frame_id in frame_ids:
    image_path = os.path.join(base_path, frame_id, 'camera_front_blur')
    annotation_path = os.path.join(base_path, frame_id, 'annotations')
    features = extract_features(image_path, annotation_path)
    print(f'Frame {frame_id} features: {features}')

Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2024-7-12 Python-3.10.12 torch-2.3.0+cu121 CPU

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape...

Frame 007674 features: {'vehicles': 23, 'pedestrians': 6, 'traffic_signs': 20, 'traffic_signals': 7, 'pole_objects': 11, 'vulnerable_vehicles': 11, 'traffic_guides': 2}
Frame 009158 features: {'vehicles': 39, 'pedestrians': 4, 'traffic_signs': 16, 'traffic_signals': 3, 'pole_objects': 9, 'vulnerable_vehicles': 9, 'traffic_guides': 0}
Frame 018591 features: {'vehicles': 29, 'pedestrians': 6, 'traffic_signs': 24, 'traffic_signals': 7, 'pole_objects': 21, 'vulnerable_vehicles': 4, 'traffic_guides': 0}
Frame 023996 features: {'vehicles': 20, 'pedestrians': 9, 'traffic_signs': 13, 'traffic_signals': 9, 'pole_objects': 27, 'vulnerable_vehicles': 2, 'traffic_guides': 66}
Frame 029229 features: {'vehicles': 24, 'pedestrians': 7, 'traffic_signs': 70, 'traffic_signals': 6, 'pole_objects': 0, 'vulnerable_vehicles': 3, 'traffic_guides': 4}
Frame 044953 features: {'vehicles': 8, 'pedestrians': 2, 'traffic_signs': 5, 'traffic_signals': 0, 'pole_objects': 14, 'vulnerable_vehicles': 1, 'traffic_guides': 0}
Frame 062592 features: {'vehicles': 1, 'pedestrians': 2, 'traffic_signs': 11, 'traffic_signals': 0, 'pole_objects': 0, 'vulnerable_vehicles': 0, 'traffic_guides': 0}
Frame 065838 features: {'vehicles': 46, 'pedestrians': 4, 'traffic_signs': 14, 'traffic_signals': 25, 'pole_objects': 32, 'vulnerable_vehicles': 1, 'traffic_guides': 1}
Frame 070221 features: {'vehicles': 29, 'pedestrians': 4, 'traffic_signs': 21, 'traffic_signals': 8, 'pole_objects': 30, 'vulnerable_vehicles': 1, 'traffic_guides': 3}
Frame 082291 features: {'vehicles': 22, 'pedestrians': 1, 'traffic_signs': 12, 'traffic_signals': 0, 'pole_objects': 0, 'vulnerable_vehicles': 0, 'traffic_guides': 0}
Frame 083430 features: {'vehicles': 4, 'pedestrians': 0, 'traffic_signs': 19, 'traffic_signals': 20, 'pole_objects': 0, 'vulnerable_vehicles': 0, 'traffic_guides': 0}
Frame 087912 features: {'vehicles': 32, 'pedestrians': 0, 'traffic_signs': 29, 'traffic_signals': 21, 'pole_objects': 41, 'vulnerable_vehicles': 0, 'traffic_guides': 0}

In [ ]:
import os
import json

def load_annotations(file_path):
    with open(file_path, 'r') as file:
        annotations = json.load(file)
    return annotations

def extract_annotation_details(annotations):
    details = []
    for annotation in annotations:
        properties = annotation.get('properties', {})

        detail = {
            "class": properties.get("class", "Unknown"),
            "unclear": properties.get("unclear", "Unknown"),
            "traffic_content_visible": properties.get("traffic_content_visible", "Unknown"),
            "is_for_construction": properties.get("is_for_construction", "Unknown"),
            "is_for_ego_road": properties.get("is_for_ego_road", "Unknown"),
            "is_for_ego_lane": properties.get("is_for_ego_lane", "Unknown"),
            "is_for_other_traffic_participant": properties.get("is_for_other_traffic_participant", "Unknown"),
            "is_on_dynamic_object": properties.get("is_on_dynamic_object", "Unknown"),
            "occlusion_ratio": properties.get("occlusion_ratio", "Unknown"),
            "size_3d_length": properties.get("size_3d_length", "Unknown"),
            "size_3d_width": properties.get("size_3d_width", "Unknown"),
            "size_3d_height": properties.get("size_3d_height", "Unknown"),
            "location_3d": properties.get("location_3d", {}).get("coordinates", "Unknown")
        }

        details.append(detail)

    return details

def print_annotation_details(details):
    for detail in details:
        print(f"Class: {detail['class']}")
        print(f"Unclear: {detail['unclear']}")
        print(f"Traffic Content Visible: {detail['traffic_content_visible']}")
        print(f"Is for Construction: {detail['is_for_construction']}")
        print(f"Is for Ego Road: {detail['is_for_ego_road']}")
        print(f"Is for Ego Lane: {detail['is_for_ego_lane']}")
        print(f"Is for Other Traffic Participant: {detail['is_for_other_traffic_participant']}")
        print(f"Is on Dynamic Object: {detail['is_on_dynamic_object']}")

        print('-' * 50)

def process_all_frames(frame_ids, base_path):
    for frame_id in frame_ids:
        annotation_file_path = os.path.join(base_path, frame_id, 'annotations', 'object_detection.json')
        if os.path.exists(annotation_file_path):
            print(f"Processing frame: {frame_id}")
            annotations = load_annotations(annotation_file_path)
            annotation_details = extract_annotation_details(annotations)
            print_annotation_details(annotation_details)
        else:
            print(f"Annotation file not found for frame: {frame_id}")

# Example usage
frame_ids = ['007674', '009158', '018591', '023996', '029229', '044953', '062592', '065838', '070221', '082291', '083430', '087912']
base_path = '/content/drive/My Drive/Colab Notebooks/ZODMiniDataset/Frames/single_frames'

process_all_frames(frame_ids, base_path)

Streaming output truncated to the last 5000 lines.
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: True
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: TrafficSignal
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: True
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: False
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: True
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: False
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSignal
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficGuide
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: False
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: False
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficGuide
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: False
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: False
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficGuide
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: False
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: False
Is for Other Traffic Participant: True
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: False
Is for Ego Lane: False
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: TrafficSign
Unclear: False
Traffic Content Visible: True
Is for Construction: False
Is for Ego Road: True
Is for Ego Lane: True
Is for Other Traffic Participant: False
Is on Dynamic Object: False
--------------------------------------------------
Class: Pedestrian
Unclear: True
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: VulnerableVehicle
Unclear: True
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: True
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Pedestrian
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Pedestrian
Unclear: True
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: Vehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------
Class: VulnerableVehicle
Unclear: False
Traffic Content Visible: Unknown
Is for Construction: Unknown
Is for Ego Road: Unknown
Is for Ego Lane: Unknown
Is for Other Traffic Participant: Unknown
Is on Dynamic Object: Unknown
--------------------------------------------------

In [ ]:
import json
import os
from collections import defaultdict

def extract_annotations(annotation_path):
    traffic_signs_path = os.path.join(annotation_path, 'object_detection.json')
    with open(traffic_signs_path, 'r') as file:
        annotations = json.load(file)
    return annotations

def get_unique_properties(annotations):
    unique_properties = defaultdict(set)
    for annotation in annotations:
        properties = annotation.get('properties', {})
        for key, value in properties.items():
            # Convert any dictionary values to a string
            if isinstance(value, dict):
                value = json.dumps(value)
            # Convert any list values to a tuple
            elif isinstance(value, list):
                value = tuple(value)
            unique_properties[key].add(value)
    return unique_properties

# Example usage for multiple frames
frame_ids = ['007674', '009158', '018591', '023996', '029229', '044953', '062592', '065838', '070221', '082291', '083430', '087912']
base_path = '/content/drive/My Drive/Colab Notebooks/ZODMiniDataset/Frames/single_frames'

all_unique_properties = defaultdict(set)

for frame_id in frame_ids:
    annotation_path = os.path.join(base_path, frame_id, 'annotations')
    annotations = extract_annotations(annotation_path)
    unique_properties = get_unique_properties(annotations)
    for key, values in unique_properties.items():
        all_unique_properties[key].update(values)

# Print out all unique properties and their values
for key, values in all_unique_properties.items():
    print(f"Property: {key}")
    print(f"Values: {values}\n")

Property: annotation_uuid

In [ ]:
!pip install opencv-python torch torchvision pandas

Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (4.8.0.76)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.3.0+cu121)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (0.18.0+cu121)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.10/dist-packages (from opencv-python) (1.25.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.6.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch) (2.3.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch)
  Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (21.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 57.9 MB/s eta 0:00:00
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision) (9.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch) (1.3.0)
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.82 nvidia-nvtx-cu12-12.1.105

In [ ]:
import cv2
import torch

# Load a pre-trained YOLOv5 model (latest version)
model = torch.hub.load('ultralytics/yolov5', 'yolov5x')

def detect_objects(image_path):
    img = cv2.imread(image_path)
    results = model(img)
    return results.pandas().xyxy[0]

# Extract features from an image
def extract_features(image_path):
    detections = detect_objects(image_path)
    features = {
        'vehicles': len(detections[detections['name'] == 'car']),
        'pedestrians': len(detections[detections['name'] == 'person'])
    }
    return features

# Example usage
image_path = '/content/drive/My Drive/Colab Notebooks/ZODMiniDataset/Frames/single_frames/087912/camera_front blur'
features = extract_features(image_path)
print(features)

/usr/local/lib/python3.10/dist-packages/torch/hub.py:293: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip

requirements: Ultralytics requirements ['gitpython>=3.1.30', 'pillow>=10.3.0', 'requests>=2.32.0'] not found, attempting AutoUpdate...
Collecting gitpython>=3.1.30
  Downloading GitPython-3.1.43-py3-none-any.whl (207 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 4.6 MB/s eta 0:00:00
Collecting pillow>=10.3.0
  Downloading pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 67.6 MB/s eta 0:00:00
Collecting requests>=2.32.0
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 113.5 MB/s eta 0:00:00
Collecting gitdb<5,>=4.0.1 (from gitpython>=3.1.30)
  Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 130.3 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.0) (2024.7.4)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython>=3.1.30)
  Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
Installing collected packages: smmap, requests, pillow, gitdb, gitpython
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.4.0
    Uninstalling Pillow-9.4.0:
      Successfully uninstalled Pillow-9.4.0
Successfully installed gitdb-4.0.11 gitpython-3.1.43 pillow-10.4.0 requests-2.32.3 smmap-5.0.1

requirements: AutoUpdate success ✅ 14.8s, installed 3 packages: ['gitpython>=3.1.30', 'pillow>=10.3.0', 'requests>=2.32.0']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

YOLOv5 🚀 2024-7-13 Python-3.10.12 torch-2.3.0+cu121 CPU

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5x.pt to yolov5x.pt...
100%|██████████| 166M/166M [00:01<00:00, 161MB/s]

Fusing layers...
YOLOv5x summary: 444 layers, 86705005 parameters, 0 gradients, 205.5 GFLOPs
Adding AutoShape...

AttributeError: 'NoneType' object has no attribute 'shape'